entryPoints:
  dev-http:
    address: ':80'
  dev-https:
    address: ':443'
    http:
      tls:
        options: default

providers:
  file:
    directory: /etc/traefik/conf.d
    watch: true

log:
  level: DEBUG
  format: json
accessLog: {}
